import type { Product } from '../types/product';

export const productsData: Product[] = [
  {
    name: 'Body Care',
    price: '220,000đ',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    info: 'Sản phẩm chăm sóc cơ thể Body Care với thành phần tự nhiên, giúp nuôi dưỡng làn da mềm mại và mịn màng.',
    sale: true,
  },
  {
    name: 'Body Max Cream',
    price: '730,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800&auto=format&fit=crop',
    info: 'Body Max là dòng sản phẩm cao cấp dành cho spa, hỗ trợ săn chắc da và cải thiện độ đàn hồi hiệu quả.',
    sale: true,
  },
  {
    name: 'Body Soap Bar',
    price: '780,000đ',
    category: 'Cosmetics',
    image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=800&auto=format&fit=crop',
    info: 'Xà phòng tắm thảo mộc thiên nhiên, làm sạch sâu và mang lại hương thơm dễ chịu suốt cả ngày.',
    sale: false,
  },
  {
    name: 'Pure Face Oil',
    price: '300,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    info: 'Dầu dưỡng da mặt Face Oil giúp cân bằng độ ẩm, ngăn ngừa lão hóa và làm sáng tông màu da.',
    sale: true,
  },
  {
    name: 'Hair Shine Spray',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop',
    info: 'Tinh chất dưỡng tóc chuyên sâu, phục hồi tóc hư tổn và mang lại vẻ bóng mượt tự nhiên.',
    sale: false,
  },
  {
    name: 'Lipstick Pro Matte',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop',
    info: 'Son môi Lipstick Pro với bảng màu thời thượng, chất son mịn lì và giàu dưỡng chất chăm sóc môi.',
    sale: false,
  },
  {
    name: 'Nail Polish Glossy',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop',
    info: 'Sơn móng tay chất lượng cao, khô nhanh và bền màu, không gây hại cho bề mặt móng.',
    sale: false,
  },
  {
    name: 'Body Care',
    price: '220,000đ',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    info: 'Sản phẩm chăm sóc cơ thể Body Care với thành phần tự nhiên, giúp nuôi dưỡng làn da mềm mại và mịn màng.',
    sale: true,
  },
  {
    name: 'Body Max',
    price: '730,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800&auto=format&fit=crop',
    info: 'Body Max là dòng sản phẩm cao cấp dành cho spa, hỗ trợ săn chắc da và cải thiện độ đàn hồi hiệu quả.',
    sale: true,
  },
  {
    name: 'Body Sop',
    price: '780,000đ',
    category: 'Cosmetics',
    image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=800&auto=format&fit=crop',
    info: 'Xà phòng tắm thảo mộc thiên nhiên, làm sạch sâu và mang lại hương thơm dễ chịu suốt cả ngày.',
    sale: false,
  },
  {
    name: 'Face Oil',
    price: '300,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    info: 'Dầu dưỡng da mặt Face Oil giúp cân bằng độ ẩm, ngăn ngừa lão hóa và làm sáng tông màu da.',
    sale: true,
  },
  {
    name: 'Hair Shine',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop',
    info: 'Tinh chất dưỡng tóc chuyên sâu, phục hồi tóc hư tổn và mang lại vẻ bóng mượt tự nhiên.',
    sale: false,
  },
  {
    name: 'Lipstick Pro',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop',
    info: 'Son môi Lipstick Pro với bảng màu thời thượng, chất son mịn lì và giàu dưỡng chất chăm sóc môi.',
    sale: false,
  },
  {
    name: 'Nail Polish',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop',
    info: 'Sơn móng tay chất lượng cao, khô nhanh và bền màu, không gây hại cho bề mặt móng.',
    sale: false,
  },
  {
    name: 'Body Care',
    price: '220,000đ',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    info: 'Sản phẩm chăm sóc cơ thể Body Care với thành phần tự nhiên, giúp nuôi dưỡng làn da mềm mại và mịn màng.',
    sale: true,
  },
  {
    name: 'Body Max',
    price: '730,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800&auto=format&fit=crop',
    info: 'Body Max là dòng sản phẩm cao cấp dành cho spa, hỗ trợ săn chắc da và cải thiện độ đàn hồi hiệu quả.',
    sale: true,
  },
  {
    name: 'Body Sop',
    price: '780,000đ',
    category: 'Cosmetics',
    image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=800&auto=format&fit=crop',
    info: 'Xà phòng tắm thảo mộc thiên nhiên, làm sạch sâu và mang lại hương thơm dễ chịu suốt cả ngày.',
    sale: false,
  },
  {
    name: 'Face Oil',
    price: '300,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    info: 'Dầu dưỡng da mặt Face Oil giúp cân bằng độ ẩm, ngăn ngừa lão hóa và làm sáng tông màu da.',
    sale: true,
  },
  {
    name: 'Hair Shine',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop',
    info: 'Tinh chất dưỡng tóc chuyên sâu, phục hồi tóc hư tổn và mang lại vẻ bóng mượt tự nhiên.',
    sale: false,
  },
  {
    name: 'Lipstick Pro',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop',
    info: 'Son môi Lipstick Pro với bảng màu thời thượng, chất son mịn lì và giàu dưỡng chất chăm sóc môi.',
    sale: false,
  },
  {
    name: 'Nail Polish',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop',
    info: 'Sơn móng tay chất lượng cao, khô nhanh và bền màu, không gây hại cho bề mặt móng.',
    sale: false,
  },
  {
    name: 'Body Care',
    price: '220,000đ',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    info: 'Sản phẩm chăm sóc cơ thể Body Care với thành phần tự nhiên, giúp nuôi dưỡng làn da mềm mại và mịn màng.',
    sale: true,
  },
  {
    name: 'Body Max',
    price: '730,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800&auto=format&fit=crop',
    info: 'Body Max là dòng sản phẩm cao cấp dành cho spa, hỗ trợ săn chắc da và cải thiện độ đàn hồi hiệu quả.',
    sale: true,
  },
  {
    name: 'Body Sop',
    price: '780,000đ',
    category: 'Cosmetics',
    image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=800&auto=format&fit=crop',
    info: 'Xà phòng tắm thảo mộc thiên nhiên, làm sạch sâu và mang lại hương thơm dễ chịu suốt cả ngày.',
    sale: false,
  },
  {
    name: 'Face Oil',
    price: '300,000đ',
    category: 'Spa Fashion',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    info: 'Dầu dưỡng da mặt Face Oil giúp cân bằng độ ẩm, ngăn ngừa lão hóa và làm sáng tông màu da.',
    sale: true,
  },
  {
    name: 'Hair Shine',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop',
    info: 'Tinh chất dưỡng tóc chuyên sâu, phục hồi tóc hư tổn và mang lại vẻ bóng mượt tự nhiên.',
    sale: false,
  },
  {
    name: 'Lipstick Pro',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop',
    info: 'Son môi Lipstick Pro với bảng màu thời thượng, chất son mịn lì và giàu dưỡng chất chăm sóc môi.',
    sale: false,
  },
  {
    name: 'Nail Polish',
    price: '580,000đ',
    category: 'Popular',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop',
    info: 'Sơn móng tay chất lượng cao, khô nhanh và bền màu, không gây hại cho bề mặt móng.',
    sale: false,
  },
];
